const GRID_COLOR = "#444444";
const GRID_WIDTH_MOD = 24;
const MIN_UNIT_SIZE_FOR_GRID_DRAW = 8;

const SCROLL_SCALE_INCREMENT = 1;
const ROOT_VIEW_PADDING = 10;

const VMPH_THICKNESS = 50;

const GRASS_FIELD_COLOR = "#008800";
const SHALLOW_WATER_FIELD_COLOR = "#0000dd";
const DEEP_WATER_FIELD_COLOR = "#000088";
const PLANT_COLOR = "#004400";

const RABBIT_MALE_COLOR = "#779999";
const RABBIT_FEMALE_COLOR = "#bb9999";
const FOX_MALE_COLOR = "#bb8822";
const FOX_FEMALE_COLOR = "#bb4422";

const RABBIT_MALE_DRAW_SIZE = 0.65;
const RABBIT_FEMALE_DRAW_SIZE = 0.55;
const FOX_MALE_DRAW_SIZE = 1.10;
const FOX_FEMALE_DRAW_SIZE = 0.95;
const CHILD_SIZE_DRAW_MOD = 0.6;

const VOID_FIELD_ID = 0;
const GRASS_FIELD_ID = 1;
const SHALLOW_WATER_FIELD_ID = 2;
const DEEP_WATER_FIELD_ID = 3;


const ANIMAL_TYPE_ID = 0;
const RABBIT_TYPE_ID = 1;
const FOX_TYPE_ID = 2;

const HUNGER_NEED_ID = 0;
const THIRST_NEED_ID = 1;
const BREEDING_NEED_ID = 2;